site_name: Freqtrade
theme:
  name: material
  logo: 'images/logo.png'
  palette:
    primary: 'blue grey'
    accent: 'deep orange'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: false