site_name: Freqtrade
nav:
    - About: about.md
    - Installation: pre-requisite.md
    - Configuratioon: configuration.md
    - Start the bot: bot-usage.md
    - Bot optimization: bot-optimization.md
    - Backtesting: backtesting.md
    - Hyperopt: hyperopt.md
    - Plotting: plotting.md
    - Telegram usage: telegram-usage.md
theme:
  name: material
  logo: 'images/logo.png'
  palette:
    primary: 'blue grey'
    accent: 'tear'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: false