---
version: '3'
services:
  ft_vscode:
    build:
      context: ..
      dockerfile: ".devcontainer/Dockerfile"
    volumes:
      # Allow git usage within container
      - "/home/${USER}/.ssh:/home/ftuser/.ssh:ro"
      - "/home/${USER}/.gitconfig:/home/ftuser/.gitconfig:ro"
      - ..:/freqtrade:cached
      # Persist bash-history
      - freqtrade-vscode-server:/home/ftuser/.vscode-server
      - freqtrade-bashhistory:/home/ftuser/commandhistory
    # Expose API port
    ports:
      - "127.0.0.1:8080:8080"
    command: /bin/sh -c "while sleep 1000; do :; done"


volumes:
  freqtrade-vscode-server:
  freqtrade-bashhistory:
