---
version: '3'
services:
  ft_vscode:
    build:
      context: ..
      dockerfile: "Dockerfile.develop"
    volumes:
      - ..:/freqtrade:cached
      - freqtrade-vscode-server:/home/ftuser/.vscode-server
      - freqtrade-bashhistory:/home/ftuser/commandhistory

    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  freqtrade-vscode-server:
  freqtrade-bashhistory:
